In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True) 

In [4]:
independent=dataset[['age', 'bmi','children','sex_male', 'smoker_yes']]

In [5]:
dependent=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
X_train=scx.fit_transform(X_train)
X_test=scx.transform(X_test)

In [8]:
from sklearn.preprocessing import StandardScaler
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [9]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(X_train,y_train)

C:\Users\deepa\ANACONDA3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000)

In [10]:
regressor.intercept_

array([0.34961713])

In [11]:
regressor.n_support_

array([410], dtype=int32)

In [12]:
regressor.support_

array([  2,   4,   6,   8,   9,  12,  13,  15,  21,  22,  25,  26,  29,
        30,  33,  36,  37,  39,  41,  44,  45,  46,  47,  52,  54,  58,
        59,  61,  66,  68,  69,  70,  71,  72,  75,  76,  85,  87,  90,
        91,  92,  95, 100, 104, 105, 107, 113, 117, 118, 121, 123, 125,
       126, 129, 132, 138, 147, 149, 153, 155, 158, 162, 164, 165, 168,
       169, 174, 177, 178, 179, 183, 187, 192, 193, 195, 197, 199, 200,
       201, 202, 203, 204, 206, 207, 209, 211, 212, 213, 214, 215, 218,
       220, 227, 231, 233, 236, 237, 238, 239, 240, 241, 242, 243, 245,
       247, 251, 253, 255, 257, 259, 263, 264, 266, 267, 273, 274, 276,
       279, 281, 285, 286, 295, 296, 297, 300, 308, 312, 315, 317, 319,
       321, 322, 323, 326, 331, 334, 335, 337, 338, 343, 344, 347, 348,
       349, 351, 353, 357, 360, 361, 364, 365, 366, 370, 373, 375, 376,
       382, 384, 386, 387, 388, 389, 391, 392, 395, 397, 399, 400, 401,
       410, 412, 413, 418, 421, 422, 423, 424, 426, 427, 428, 43

In [13]:
y_pred=regressor.predict(X_test)

In [14]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8158353481270235

In [15]:
import pickle
filename="finalized_model_SVMR-X&Y.sav"
filename1='scx.pkl'
filename2='scy.pkl'
pickle.dump(regressor,open(filename,'wb'))
pickle.dump(scx,open(filename1,'wb'))
pickle.dump(scy,open(filename2,'wb'))

In [16]:
preinput=scx.transform([[23,33,3,1,0]])
preinput

C:\Users\deepa\ANACONDA3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.17608405,  0.36064528,  1.59428492,  1.02378711, -0.50466988]])

In [17]:
loaded_model=pickle.load(open("finalized_model_SVMR-X&Y.sav",'rb'))
scx=pickle.load(open('scx.pkl','rb'))
scy=pickle.load(open('scy.pkl','rb'))

In [18]:
result=loaded_model.predict(preinput)
result

array([-0.79025561])

In [19]:
preoutput=scy.inverse_transform([result])
preoutput

array([[3849.60912671]])